### ISSUE TITLE
Add missing license headers

### ISSUE THREAD

**Issue by BalassaMarton** [morganstanley/dotnet-please#10]
License headers are missing from all code files. We also need a template for this.
BTW is this really necessary? We already put the license and notice files in the repo root which implies that they apply to all the files. Is this a strict legal requirement? Can we add an action to check the header?

**Comment by psmulovics** [comment]
There are github actions already out there responsible for checking the header, and @bingenito did ran similar tool to add headers for crossroads earlier.

**Comment by bingenito** [comment]
I added manually
