### ISSUE TITLE
ManagePackageVersionsCentrally

### ISSUE THREAD

**Issue by Krudonix** [morganstanley/dotnet-please#54]
Hi,

Awesome tool.

Please add support for ManagePackageVersionsCentrally.

Unless i'm missing something.

Thanks,
Daniel

**Comment by BalassaMarton** [comment]
Hi @Krudonix, how do you mean? What command should we add or improve?
You can do `please pull package versions` to extract the explicit versions from `PackageReference`s into your `Directory.Packages.props` file, or `please restore package versions` to migrate back to individual versioning.

**Comment by Krudonix** [comment]
I totally jumped the gun here.

I was tyring to use please consolidate packages to try update the version of the package totally getting the purpose of the command wrong. 

Please delete ;) Apologies for being an idiot
